name: ft_transcendence

services:
  ms-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - ms-auth
    environment:
      - NODE_ENV=production
  
  ms-auth:
    image: ft_transcendence-ms-auth:latest
    ports:
      - '3001:3001'
    volumes:
      - ./prisma/auth.db:/app/prisma/auth.db
    environment:
      - NODE_ENV=production 